const router = require('express').Router();
const Business= require('../webservices/eventMangementController');
//const authHandler = require('../middleware/auth_handler');

router.post('/addEvent',Business.addEvent);
 router.get('/latestEvents',Business.latestEvents);
  router.post('/allEvent',Business.allEvent);
 router.post('/myAllEvents',Business.myAllEvents);
 router.get('/eventLocation',Business.eventLocation);
 router.post('/locationDetail',Business.locationDetail);
 router.post('/myBooking',Business.myBooking);
 router.post('/eventsPending',Business.eventsPending);
 router.post('/eventsConfirmed',Business.eventsConfirmed);
 router.post('/eventsCancelled',Business.eventsCancelled);
 router.post('/eventsCompleted',Business.eventsCompleted);
 router.post('/confirmEventStatus',Business.confirmEventStatus);
 router.post('/rejectEventStatus',Business.rejectEventStatus);
 router.post('/bookingEvent',Business.bookingEvent);
 router.post('/booking',Business.booking);
 router.post('/eventDescription',Business.eventDescription);
 router.post('/filterEvent',Business.filterEvent);
 router.post('/myBookingShow',Business.myBookingShow);
 router.post('/filterEventsPending',Business.filterEventsPending);
 router.post('/filterEventsConfirm',Business.filterEventsConfirm);
 //router.post('/bookingEvent',Business.bookingEvent);
 router.post('/addCustomerFeedback',Business.addCustomerFeedback);
 router.post('/viewCustomerFeedback',Business.viewCustomerFeedback);
 router.post('/myEventFeedback',Business.myEventFeedback);
 router.get('/allFeedbackViews',Business.allFeedbackViews);
 router.post('/cancelBooking',Business.cancelBooking);
 router.post('/getAllEvents/',Business.getAllEvents);
 router.post('/transactionManagementFilter',Business.transactionManagementFilter);
//  router.post('/searchEventFilter',Business.searchEventFilter);
//  router.post('/getTransactionManagement',Business.getTransactionManagement);
 router.get('/avgBussinessList',Business.avgBussinessList);
module.exports = router;
